services:
  inventory-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: inventory_pass
    ports:
      - "5432:5432"
    healthcheck:
      # This physically pings the database until it gets a successful response
      test: ["CMD-SHELL", "pg_isready -U inventory_user -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  inventory-app:
    image: jahid1018/inventory-api:latest
    depends_on:
      inventory-db:
        # App will NOT start until the health check above passes
        condition: service_healthy
    environment:
      # Notice the hyphen instead of the underscore in the URL host
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory-db:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: inventory_user
      SPRING_DATASOURCE_PASSWORD: inventory_pass
    ports:
      - "8080:8080"
    restart: on-failure # If it ever crashes for another reason, try again