version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_pass
      - POSTGRES_DB=inventory_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # THIS IS NEW
  inventory-app:
    build: . # Tells Docker to look for the Dockerfile in the current directory
    container_name: inventory_app
    ports:
      - "8080:8080" # Map your laptop's 8080 to the container's 8080
    depends_on:
      - postgres # Don't start the app until the DB is running
    environment:
      # We pass the DB credentials and host directly into the container!
      - POSTGRES_HOST=postgres
      - SPRING_DATASOURCE_USERNAME=inventory_user
      - SPRING_DATASOURCE_PASSWORD=inventory_pass

volumes:
  postgres_data: