version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory_db
    ports:
      - "5432:5432" # Map localhost:5432 to container:5432
    environment:
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_pass
      - POSTGRES_DB=inventory_db
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data even if container stops

volumes:
  postgres_data: