spring.application.name=inventory-api

# Use 'postgres' as host inside Docker instead of localhost
spring.datasource.url=jdbc:postgresql://inventory_db:5432/inventory_db
spring.datasource.username=inventory_user
spring.datasource.password=inventory_pass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
server.address=0.0.0.0